services:
  db:
    image: postgres:alpine
    container_name: postgres-${PROJECT_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-wisebill-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-${PROJECT_NAME}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-wisebill-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
  
  mongo:
    image: mongo:latest  
    container_name: mongodb-${PROJECT_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:27017 
    volumes:
      - mongo-wisebill-data:/data/db 

volumes:
  postgres-wisebill-data:
  redis-wisebill-data:
  mongo-wisebill-data:
